version: '3.4'

services:
  pathmentor.web:
    container_name: pathmentor.web
    image: ${DOCKER_REGISTRY-}pathmentor.web
    build:
      context: .
      dockerfile: pathmentor.web/Dockerfile
    depends_on:
      - pathmentor.test.api
      - pathmentor.auth.api

  pathmentor.test.api:
    container_name: pathmentor.test.api
    image: ${DOCKER_REGISTRY-}pathmentor.test.api
    build:
      context: .
      dockerfile: PathMentor.Test.API/Dockerfile
    depends_on:
      - pathmentormssqlserver

  pathmentor.auth.api:
    container_name: pathmentor.auth.api
    image: ${DOCKER_REGISTRY-}pathmentor.auth.api
    build:
      context: .
      dockerfile: PathMentor.Auth.API/Dockerfile
    depends_on:
      - pathmentormssqlserver

  pathmentormssqlserver:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "Password_123"
        ACCEPT_EULA: "Y"
        MSSQL_PID: "Express"
    ports:
        - "1433:1433" 
