version: '3.4'

services:
  pathmentormodeldatabase:
    image: postgres:alpine
    container_name: pathmentor.model.database
    environment:
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256
      POSTGRES_USER: ${POSTGRES_USER}
      PGUSER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: pathmentormodel
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d pathmentormodel"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

  pathmentormodelapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - ASPNETCORE_HTTPS_PORTS=443
      - ConnectionStrings__DefaultConnection=Host=pathmentor.model.database; Port=5432; Database=pathmentormodel; Username=${POSTGRES_USER}; Password=${POSTGRES_PASSWORD}; CommandTimeout=120;
    build:
      args:
        - configuration=Debug
    ports:
      - "5000:80"
      - "5001:443"
    volumes:
      - $HOME/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
      - $HOME/.aspnet/https:/root/.aspnet/https:ro
      - $HOME/.vsdbg:/remote_debugger:rw
    depends_on:
      pathmentormodeldatabase:
        condition: service_healthy

  pathmentordatasetcli:
    image: ${DOCKER_REGISTRY-}pathmentor.dataset.cli
    container_name: pathmentor.dataset.cli
    build:
      context: .
      dockerfile: pathmentor_dataset_cli/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=host=pathmentor.model.database port=5432 dbname=pathmentormodel user=${POSTGRES_USER} password=${POSTGRES_PASSWORD}
    depends_on:
      pathmentormodeldatabase:
        condition: service_healthy
