# docker compose -f docker-compose.yml -f docker-compose.*.override.yml --env-file *.env up -d --build

services:
  pathmentormodelapi:
    image: ${DOCKER_REGISTRY-}pathmentor.model.api
    container_name: pathmentor.model.api
    build:
      context: .
      dockerfile: PathMentor.Model.API/Dockerfile
    healthcheck:
      test: ["CMD-SHELL", "curl -k --fail https://localhost/health || exit"]
      interval: 60s
      timeout: 5s
      retries: 5
