// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PathMentor.Data;

#nullable disable

namespace PathMentor.Data.Migrations
{
    [DbContext(typeof(PathMentorModelDbContext))]
    [Migration("20240425173051_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InteractionSkill", b =>
                {
                    b.Property<Guid>("ContextInteractionsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContextSkillsId")
                        .HasColumnType("uuid");

                    b.HasKey("ContextInteractionsId", "ContextSkillsId");

                    b.HasIndex("ContextSkillsId");

                    b.ToTable("InteractionSkill");
                });

            modelBuilder.Entity("PathMentor.Data.Entities.Experience", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Range")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Range")
                        .IsUnique();

                    b.ToTable("Experiences");
                });

            modelBuilder.Entity("PathMentor.Data.Entities.Interaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ExperienceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LabelSkillId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SalaryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TitleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExperienceId");

                    b.HasIndex("LabelSkillId");

                    b.HasIndex("SalaryId");

                    b.HasIndex("TitleId");

                    b.ToTable("Interactions");
                });

            modelBuilder.Entity("PathMentor.Data.Entities.Salary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Range")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Range")
                        .IsUnique();

                    b.ToTable("Salaries");
                });

            modelBuilder.Entity("PathMentor.Data.Entities.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("PathMentor.Data.Entities.Title", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Titles");
                });

            modelBuilder.Entity("InteractionSkill", b =>
                {
                    b.HasOne("PathMentor.Data.Entities.Interaction", null)
                        .WithMany()
                        .HasForeignKey("ContextInteractionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PathMentor.Data.Entities.Skill", null)
                        .WithMany()
                        .HasForeignKey("ContextSkillsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PathMentor.Data.Entities.Interaction", b =>
                {
                    b.HasOne("PathMentor.Data.Entities.Experience", "Experience")
                        .WithMany("Interactions")
                        .HasForeignKey("ExperienceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PathMentor.Data.Entities.Skill", "LabelSkill")
                        .WithMany("LabelInteractions")
                        .HasForeignKey("LabelSkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PathMentor.Data.Entities.Salary", "Salary")
                        .WithMany("Interactions")
                        .HasForeignKey("SalaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PathMentor.Data.Entities.Title", "Title")
                        .WithMany("Interactions")
                        .HasForeignKey("TitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Experience");

                    b.Navigation("LabelSkill");

                    b.Navigation("Salary");

                    b.Navigation("Title");
                });

            modelBuilder.Entity("PathMentor.Data.Entities.Experience", b =>
                {
                    b.Navigation("Interactions");
                });

            modelBuilder.Entity("PathMentor.Data.Entities.Salary", b =>
                {
                    b.Navigation("Interactions");
                });

            modelBuilder.Entity("PathMentor.Data.Entities.Skill", b =>
                {
                    b.Navigation("LabelInteractions");
                });

            modelBuilder.Entity("PathMentor.Data.Entities.Title", b =>
                {
                    b.Navigation("Interactions");
                });
#pragma warning restore 612, 618
        }
    }
}
